/**
 * TornPaperDivider — standalone between-section divider.
 *
 * Renders an INLINE SVG so the browser's vector engine draws every line
 * segment at the exact display resolution — no rasterisation, no smoothing.
 *
 * Paths are high-fidelity traces of the original Framer PNG assets
 * (~2000 points each), generated by scripts/trace-torn-paper.py.
 *
 * preserveAspectRatio="none" lets the SVG stretch to fill the container
 * width while the height is controlled by CSS clamp().
 */

import { tornPaperPaths } from "./tornPaperPaths";

type TornPaperDividerColor = "red" | "black" | "white" | "grey" | "purple";

type TornPaperDividerProps = {
  color?: TornPaperDividerColor;
  flip?: boolean;
};

const fillMap: Record<TornPaperDividerColor, string> = {
  black: "#000000",
  red: "#F92524",
  white: "#ffffff",
  grey: "#EFEEED",
  purple: "#AE2CF2",
};

export default function TornPaperDivider({
  color = "black",
  flip = false,
}: TornPaperDividerProps) {
  return (
    <div
      className="relative w-full pointer-events-none select-none"
      style={{
        height: "clamp(50px, 6vw, 100px)",
        marginTop: "calc(-1 * clamp(25px, 3vw, 50px))",
        marginBottom: "calc(-1 * clamp(25px, 3vw, 50px))",
        zIndex: 10,
        ...(flip ? { transform: "scaleY(-1)" } : {}),
      }}
      aria-hidden="true"
    >
      <svg
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 2400 100"
        preserveAspectRatio="none"
        fill="none"
        style={{
          display: "block",
          width: "100%",
          height: "100%",
        }}
      >
        <path fill={fillMap[color]} d={tornPaperPaths[color]} />
      </svg>
    </div>
  );
}
