/**
 * Testimonial transcripts, baked into source at edit time.
 *
 * These used to be read via fs.readFileSync at module load from
 * public/testimonial-videos/*.txt. That worked locally but triggered
 * Next.js file tracing to pull the entire public/testimonial-videos/
 * directory (including ~420MB of MP4s) into the serverless function
 * bundle, which blew past Netlify's 50MB function-size limit.
 *
 * To add or update a transcript, paste the plain text here. Keep the
 * file HTML-free.
 */

export const testimonialTranscripts: Record<string, string> = {
  beckyParent: "For me, the importance of this program was, every kid is gonna want some amount of screen time, whether that's gaming or watching TV or whatever, and I'd much rather screen time be focused in an atmosphere where the kids know each other and they're working towards a common goal.Before, EKUZO it was a lot of just, like, gaming with random people and random times, and, this helped me get a grasp on having it be something that was more of a thing.And also, like, he has less desire to spend time scrolling YouTube when he can be practicing for his team or you know,during his practices.And so I definitely think and have seen a more focused importance of where he's spending that screen time, and so, that's what's been really great.And he knows too that by doing this program which he really loves, there's also a requirement for me for him to continue to do things like play sports and be outside and ride his bike, and so it's been a really great balance for, him and the family.",
  bradParentGirlGamer: "Hi. My name's Brad, and I'm a dad to a girl gamer.And a little while ago, my daughter came up to me and she asked me, \"Dad, how do I deal with boys online?\"And there were certainly some kids saying some things they shouldn't have been saying online.An- and it took this thing my daughter really enjoyed doing, playing games online, and it made her like it less.So I- I- I looked online.I tried to find somewhere where maybe she could have a better environment, and that's where I found Ekuzo.I found a group of coaches that are very clear with their expectations.They, they teach respect.They teach, they teach care.They treat everybody the same.And it put her on a team where she found people that she gets along with.She found people she likes being around.And it, it took this thing, online gaming, and put it in a, put it in a sphere where they're all learning real life lessons.I mean, they're learning digital citizenship.They don't call it that, but that's what it is.The coaches are very intentional about teaching behind each avatar as a real person, and this has really helped my daughter realize that every online person deserves respect, but also must give respect back.And it's been wonderful, right?As a, as a dad to a girl gamer, the team, the team atmosphere, and the- all the safety and expectations, and just joy that Ekuzo's added to her life has been a godsend.",
  debbiePotterMonroe: "Hello.My name is Debbie Potter.I'm the director of admissions at Robert F.Monroe Day School, and I'm also the founding sponsor of the esports program at Monroe partnering with EKUZO.I've seen such a huge growth in the students, in their maturity, their respect, their pride in their school.They've really turned into an amazing team.They're learning to work together, become more responsible.And all the changes that have been happening have been overflowing into their other elective classes, academic classes, and even at home.The change I've seen in them is incredible.I would recommend to anyone, whether if you're a parent, a teacher, a school administrator like me, to do it.Start your partnership with EKUZO.It's worth it.You will not regret it.Not only are you changing lives of these students, you're changing the culture of your school, more school spirit.You're giving a place for these students to belong that might have not had a place to belong before.So I 100% recommend it.",
  lauraHoganMirusAcademy: "Hi, I'm Laura Hogan, an administrator at Mirus Academy here in Katy, Texas.Now, I readily admit that I personally know very little about video games or the world of esports, and so we were interested in having an esports team here at Mirus Academy, but when it came to actually implementing this team, I didn't have the slightest idea how to begin, and that's where EKUZO really comes in.The coaches there at EKUZO took care of all the details for us, so I didn't have to spend any of my time, my very limited time, figuring out how this whole world of esports works.From establishing our school's team and organizing all of the team practices to getting all the students registered in some really impressive tournaments, EKUZO has managed all of it, taking care of all the details.And as an educator, I especially love how the grit and the determination translates over to their academic life and their personal life too, and it's that kind of growth right there that makes me really glad that we established this esports program here at Mirus Academy. EKUZO as an organization, they are reliable, knowledgeable, and they're a valuable educational vendor for us.Grateful for EKUZO and we would recommend them for any other school that's looking to implement their own esports team and need a valuable partner in the whole enterprise.",
  rajithaParent: "Shreshth learned a lot of the teamwork with esports.Problem-solving, on-the-fly problems, he used to just solve it on a daily basis.Time management.He knows that he only gets this much amount of time playing the esport, so he ensured that he learned the time management by doing so.More importantly, the very silent skill which he learnt was how to become stronger and be more resilient every time he loses a match.That's on the soft side.From the technical side, when you're playing on a platform, he automatically learned the skills like troubleshooting, the leadership skills by playing with the teams.What I believe as a parent is, it's more like a life skill for them and less on the game skills.",
  studentILearned: "I learned that you have to have a great amount of dedication for what you put in while you're in esports.When you make a mistake in, like, League, you learn from that mistake and, well, you think, \"Oh, I can't do this again.\"You can also apply that to life where if you mess up something, you learn from that mistake and, well, you're not gonna do it again.",
  studentManOfMyWord: "I have learned to be more of a man of my word, even if it's something subtle or something small.Learning how to be more of a leader, learning more of how to step up to the plate when it really matters.",
  studentThankYouEkuzo: "I've learned that hard work and teamwork pay off. I have learned to own up to my own mistakes and, be a better person.I've learned determination and anger management.Thank you EKUZO.",
  studentYouShouldJoin: "You should definitely join.It's a family.It's Everyone's together.We all love our members and you should join because when you join,you're coming into a family that loves and cares and takes care of their family members.",
};
